// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.util;

import javax.enterprise.inject.spi.InjectionPoint;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;
import java.lang.reflect.Member;
import java.util.Properties;

public class ConfigPropertyProducer_produceConfigProperty_5b9fee6055_Test {

    private InjectionPoint ip;
    private ConfigProperty configProperty;
    private static Properties props;

    @Before
    public void setUp() {
        ip = Mockito.mock(InjectionPoint.class);
        configProperty = Mockito.mock(ConfigProperty.class);
        props = new Properties();
        Mockito.when(ip.getAnnotated().getAnnotation(ConfigProperty.class)).thenReturn(configProperty);
    }

    @Test
    public void testProduceConfigPropertyValidKey() {
        String key = "valid.key";
        String expectedValue = "valid.value";
        props.setProperty(key, expectedValue);
        Mockito.when(configProperty.value()).thenReturn(key);

        String actualValue = ConfigPropertyProducer.produceConfigProperty(ip);

        Assert.assertEquals(expectedValue, actualValue);
    }

    @Test
    public void testProduceConfigPropertyInvalidKey() {
        String key = "invalid.key";
        Mockito.when(configProperty.value()).thenReturn(key);

        String actualValue = ConfigPropertyProducer.produceConfigProperty(ip);

        Assert.assertNull(actualValue);
    }
}
