// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.util;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import javax.enterprise.inject.spi.InjectionPoint;
import java.util.logging.Logger;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class LoggingProducer_produceLogger_0dae710c17_Test {

    @Mock
    private InjectionPoint injectionPoint;

    @Mock
    private Logger logger;

    private LoggingProducer loggingProducer;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
        loggingProducer = new LoggingProducer();
    }

    @Test
    public void testProduceLoggerSuccess() {
        when(injectionPoint.getMember().getDeclaringClass().getName()).thenReturn("org.agoncal.application.petstore.util");
        logger = loggingProducer.produceLogger(injectionPoint);
        assertNotNull(logger);
        assertEquals("org.agoncal.application.petstore.util", logger.getName());
    }

    @Test(expected = RuntimeException.class)
    public void testProduceLoggerException() {
        when(injectionPoint.getMember().getDeclaringClass().getName()).thenThrow(new RuntimeException());
        logger = loggingProducer.produceLogger(injectionPoint);
    }
}
