// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.util;

import javax.enterprise.inject.spi.InjectionPoint;
import java.util.logging.Logger;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class LoggingProducer_produceLogger_0dae710c17_Test {

    @Test
    public void testProduceLoggerSuccess() {
        InjectionPoint mockInjectionPoint = mock(InjectionPoint.class);
        when(mockInjectionPoint.getMember().getDeclaringClass().getName()).thenReturn("TestClassName");

        LoggingProducer loggingProducer = new LoggingProducer();
        Logger logger = loggingProducer.produceLogger(mockInjectionPoint);

        assertNotNull("Logger should not be null", logger);
        assertEquals("Logger name should match class name", "TestClassName", logger.getName());
    }

    @Test(expected = NullPointerException.class)
    public void testProduceLoggerFailure() {
        InjectionPoint mockInjectionPoint = mock(InjectionPoint.class);
        when(mockInjectionPoint.getMember().getDeclaringClass().getName()).thenReturn(null);

        LoggingProducer loggingProducer = new LoggingProducer();
        loggingProducer.produceLogger(mockInjectionPoint);
    }
}
