// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.util;

import javax.enterprise.inject.spi.InjectionPoint;
import org.junit.jupiter.api.Test;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

import java.util.logging.Logger;

class LoggingProducer_produceLogger_0dae710c17_Test {
    
    @Test
    public void testProduceLogger() {
        LoggingProducer loggingProducer = new LoggingProducer();
        InjectionPoint mockInjectionPoint = mock(InjectionPoint.class);
        when(mockInjectionPoint.getMember().getDeclaringClass()).thenReturn((Class)LoggingProducer.class);

        Logger logger = loggingProducer.produceLogger(mockInjectionPoint);

        assertNotNull(logger);
        assertEquals(LoggingProducer.class.getName(), logger.getName());
    }

    @Test
    public void testProduceLoggerWithNullInjectionPoint() {
        LoggingProducer loggingProducer = new LoggingProducer();

        assertThrows(NullPointerException.class, () -> {
            loggingProducer.produceLogger(null);
        });
    }
}
