// ********RoostGPT********
/*
Test generated by RoostGPT for test ZBIO-5239-Test using AI Type Open AI and AI Model gpt-4

Test generated for /categories_get for http method type GET in rest-assured framework

RoostTestHash=8b82be555a


*/

// ********RoostGPT********
package org.agoncal.application.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;
import java.util.Arrays;

public class categoriesGetTest {

	List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "" };
		envList = dataloader.load("src/test/java/org/agoncal/application/RoostTest/categoriesGetTest.csv", envVarsList);
	}

	@Test
	public void categoriesGet_Test() throws JSONException {
		this.setUp();
		Integer testNumber = 1;
		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty())
					? testData.get("BASE_URL") : "http://localhost:8080/applicationPetstore/rest";

			Response responseObj = given()
				.queryParam("start", testData.get("start") != null ? testData.get("start") : "")
				.queryParam("max", testData.get("max") != null ? testData.get("max") : "")
				.when()
				.get("/categories")
				.then()
				.extract()
				.response();
			JsonPath response;
			String contentType = responseObj.getContentType();

			System.out.printf("Test Case %d: categoriesGet_Test \n", testNumber++);
			System.out.println("Request: GET /categories");
			System.out.println("Status Code: " + responseObj.statusCode());
			if (testData.get("statusCode") != null) {
				MatcherAssert.assertThat(responseObj.statusCode(),
						equalTo(Integer.parseInt(testData.get("statusCode"))));
			}
			else {
				List<Integer> expectedStatusCodes = Arrays.asList(200);
				MatcherAssert.assertThat(responseObj.statusCode(), is(in(expectedStatusCodes)));
			}

			if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
				String xmlResponse = responseObj.asString();
				JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
				JSONObject jsonData = jsonResponse.getJSONObject("xml");
				String jsonString = jsonData.toString();
				response = new JsonPath(jsonString);

			}
			else if (contentType.contains("application/json")) {
				response = responseObj.jsonPath();
			}
			else {
				System.out.println("Response content type found: " + contentType
						+ ", but RoostGPT currently only supports the following response content types: application/json,text/xml,application/xml");
				continue;
			}

			if (responseObj.statusCode() == 200) {
				JSONArray respoJsonArray = new JSONArray(responseObj.asString());

				for (int it = 0; it < respoJsonArray.length(); it++) {
					response = new JsonPath(respoJsonArray.getJSONObject(it).toString());

					if (response.get("id") != null) {
						MatcherAssert.assertThat(response.get("id"), instanceOf(Integer.class));
					}

					if (response.get("version") != null) {
						MatcherAssert.assertThat(response.get("version"), instanceOf(Integer.class));
					}

					if (response.get("name") != null) {
						MatcherAssert.assertThat(response.get("name"), instanceOf(String.class));
						MatcherAssert.assertThat(response.getString("name").length(), lessThanOrEqualTo(30));

						MatcherAssert.assertThat(response.getString("name").length(), greaterThanOrEqualTo(1));

					}

					if (response.get("description") != null) {
						MatcherAssert.assertThat(response.get("description"), instanceOf(String.class));
						MatcherAssert.assertThat(response.getString("description").length(), lessThanOrEqualTo(3000));

						MatcherAssert.assertThat(response.getString("description").length(), greaterThanOrEqualTo(0));

					}

				}
			}

		}
	}

}
