// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4


// Test generated for /countries_get for http method type GET in rest-assured framework


// RoostTestHash=a284482418


package org.agoncal.application.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class countriesGetTest {
  
    @Test  
    public void countries_get_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src\test\java\org\agoncal\application\RoostTest\countriesGetTest.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("start", map.get("start") != null ? map.get("start") : "")
				.pathParam("max", map.get("max") != null ? map.get("max") : "")
                .when()
                .get("/countries")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: successful operation");
    
              if (response.jsonPath().get("id") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("id"), instanceOf(Integer.class));  
          }
    
              if (response.jsonPath().get("version") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("version"), instanceOf(Integer.class));  
          }
    
              if (response.jsonPath().get("isoCode") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("isoCode"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("isoCode").length(), lessThanOrEqualTo(2));
  
                MatcherAssert.assertThat(response.jsonPath().getString("isoCode").length(), greaterThanOrEqualTo(2));
  
          }
    
              if (response.jsonPath().get("name") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("name"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("name").length(), lessThanOrEqualTo(80));
  
                MatcherAssert.assertThat(response.jsonPath().getString("name").length(), greaterThanOrEqualTo(2));
  
          }
    
              if (response.jsonPath().get("printableName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("printableName"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("printableName").length(), lessThanOrEqualTo(80));
  
                MatcherAssert.assertThat(response.jsonPath().getString("printableName").length(), greaterThanOrEqualTo(2));
  
          }
    
              if (response.jsonPath().get("iso3") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("iso3"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("iso3").length(), lessThanOrEqualTo(3));
  
                MatcherAssert.assertThat(response.jsonPath().getString("iso3").length(), greaterThanOrEqualTo(3));
  
          }
    
              if (response.jsonPath().get("numcode") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("numcode"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("numcode").length(), lessThanOrEqualTo(3));
  
                MatcherAssert.assertThat(response.jsonPath().getString("numcode").length(), greaterThanOrEqualTo(3));
  
          }
				}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
