// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.view;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class AbstractBean_getParam_af741b4b12_Test {

    @Mock
    private FacesContext facesContext;

    @Mock
    private ExternalContext externalContext;

    private Map<String, String> parameterMap;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);

        parameterMap = new HashMap<>();
        when(facesContext.getExternalContext()).thenReturn(externalContext);
        when(externalContext.getRequestParameterMap()).thenReturn(parameterMap);
    }

    @Test
    public void testGetParam() {
        parameterMap.put("testParam", "testValue");

        String result = getParam("testParam");
        assertEquals("testValue", result);
    }

    @Test
    public void testGetParamNonExistent() {
        String result = getParam("nonExistentParam");
        assertEquals(null, result);
    }

    protected String getParam(String param) {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String, String> map = context.getExternalContext().getRequestParameterMap();
        return map.get(param);
    }
}
