// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.view;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class AbstractBean_addWarningMessage_863516008c_Test {

    @Mock
    private FacesContext facesContext;

    @Mock
    private FacesMessage facesMessage;

    private AbstractBean abstractBean;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
        abstractBean = new AbstractBean();
        abstractBean.facesContext = facesContext;
    }

    @Test
    public void testAddWarningMessage_Success() {
        when(facesContext.getMessage(anyString(), any(Object[].class))).thenReturn("Test Warning Message");
        abstractBean.addWarningMessage("Test Warning Message", "TestArg");
        verify(facesContext).addMessage(null, facesMessage);
    }

    @Test(expected = NullPointerException.class)
    public void testAddWarningMessage_NullPointerException() {
        when(facesContext.getMessage(anyString(), any(Object[].class))).thenThrow(new NullPointerException());
        abstractBean.addWarningMessage("Test Warning Message", "TestArg");
    }
}
