// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.view;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.util.Locale;
import java.util.ResourceBundle;

public class AbstractBean_getMessage_41807df738_Test {

    @Test
    public void testGetMessage() {
        FacesContext facesContext = Mockito.mock(FacesContext.class);
        Mockito.when(facesContext.getViewRoot().getLocale()).thenReturn(Locale.US);

        String msgKey = "key";
        Object[] args = new Object[]{"arg1", "arg2"};

        AbstractBean abstractBean = new AbstractBean();
        String result = abstractBean.getMessage(facesContext, msgKey, args);

        Assertions.assertNotNull(result);
        Assertions.assertNotEquals("", result);
    }

    @Test
    public void testGetMessageWithNonexistentKey() {
        FacesContext facesContext = Mockito.mock(FacesContext.class);
        Mockito.when(facesContext.getViewRoot().getLocale()).thenReturn(Locale.US);

        String msgKey = "nonexistentKey";
        Object[] args = new Object[]{"arg1", "arg2"};

        AbstractBean abstractBean = new AbstractBean();

        Assertions.assertThrows(MissingResourceException.class, () -> abstractBean.getMessage(facesContext, msgKey, args));
    }
}
