// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.view;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.util.Locale;
import java.util.ResourceBundle;

import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.class)
public class AbstractBean_addErrorMessage_c5f6545bb7_Test {

    private AbstractBean abstractBean;
    
    @Mock
    private FacesContext facesContext;
    
    @Mock
    private ResourceBundle resourceBundle;

    @Before
    public void setUp() {
        when(facesContext.getViewRoot().getLocale()).thenReturn(Locale.US);
        when(facesContext.getCurrentInstance()).thenReturn(facesContext);
        when(ResourceBundle.getBundle(anyString(), any(Locale.class), any(ClassLoader.class))).thenReturn(resourceBundle);
        when(resourceBundle.getString(anyString())).thenReturn("test message");
    }

    @Test
    public void testAddErrorMessage() {
        abstractBean.addErrorMessage("test message", "arg1", "arg2");
        verify(facesContext, times(1)).addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "test message", null));
    }

    @Test
    public void testAddErrorMessageWithoutArgs() {
        abstractBean.addErrorMessage("test message");
        verify(facesContext, times(1)).addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "test message", null));
    }
}
