// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.view;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import java.util.HashMap;
import java.util.Map;

import static org.mockito.Mockito.when;

public class AbstractBean_getParamId_c151932853_Test {

    @InjectMocks
    AbstractBean abstractBean;

    @Mock
    FacesContext facesContext;

    @Mock
    ExternalContext externalContext;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetParamIdSuccess() {
        Map<String, String> requestParameterMap = new HashMap<>();
        requestParameterMap.put("testParam", "12345");

        when(facesContext.getExternalContext()).thenReturn(externalContext);
        when(externalContext.getRequestParameterMap()).thenReturn(requestParameterMap);

        Long result = abstractBean.getParamId("testParam");
        Assert.assertEquals(Long.valueOf(12345), result);
    }

    @Test(expected = NumberFormatException.class)
    public void testGetParamIdNumberFormatException() {
        Map<String, String> requestParameterMap = new HashMap<>();
        requestParameterMap.put("testParam", "notANumber");

        when(facesContext.getExternalContext()).thenReturn(externalContext);
        when(externalContext.getRequestParameterMap()).thenReturn(requestParameterMap);

        abstractBean.getParamId("testParam");
    }

    @Test(expected = NullPointerException.class)
    public void testGetParamIdNullPointerException() {
        Map<String, String> requestParameterMap = new HashMap<>();

        when(facesContext.getExternalContext()).thenReturn(externalContext);
        when(externalContext.getRequestParameterMap()).thenReturn(requestParameterMap);

        abstractBean.getParamId("testParam");
    }
}
