// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Address_hashCode_5a2657087a_Test {

    private Address address1;
    private Address address2;

    @BeforeEach
    public void setup() {
        Country country = new Country("US","United States","United States","USA","840");
        address1 = new Address("123 Main St", "Springfield", "12345", country);
        address2 = new Address("123 Main St", "Springfield", "12345", country);
    }

    @Test
    public void testHashCode_SameObject() {
        int hashCode1 = address1.hashCode();
        int hashCode2 = address1.hashCode();
        assertEquals(hashCode1, hashCode2, "Hash codes of the same object should be equal");
    }

    @Test
    public void testHashCode_DifferentObjects_SameValues() {
        int hashCode1 = address1.hashCode();
        int hashCode2 = address2.hashCode();
        assertEquals(hashCode1, hashCode2, "Hash codes of different objects with same values should be equal");
    }

    @Test
    public void testHashCode_DifferentObjects_DifferentValues() {
        address2.setStreet1("456 Elm St");
        int hashCode1 = address1.hashCode();
        int hashCode2 = address2.hashCode();
        assertEquals(false, hashCode1 == hashCode2, "Hash codes of different objects with different values should not be equal");
    }
}
