// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Category_toString_ceffa8036e_Test {

    @Test
    public void testToString() {
        Category category = new Category();
        category.setName("Pets");
        assertEquals("Pets", category.toString());
    }

    @Test
    public void testToString_Null() {
        Category category = new Category();
        category.setName(null);
        assertNull(category.toString());
    }
}
