// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Category_equals_f2d574000d_Test {

    @Test
    public void testEqualsSameObject() {
        Category category1 = new Category("Category1", "Description1");
        assertTrue(category1.equals(category1));
    }

    @Test
    public void testEqualsDifferentType() {
        Category category1 = new Category("Category1", "Description1");
        String notACategory = "Not a Category";
        assertFalse(category1.equals(notACategory));
    }

    @Test
    public void testEqualsNull() {
        Category category1 = new Category("Category1", "Description1");
        assertFalse(category1.equals(null));
    }

    @Test
    public void testEqualsDifferentCategory() {
        Category category1 = new Category("Category1", "Description1");
        Category category2 = new Category("Category2", "Description2");
        assertFalse(category1.equals(category2));
    }

    @Test
    public void testEqualsSameCategoryName() {
        Category category1 = new Category("Category", "Description1");
        Category category2 = new Category("Category", "Description2");
        assertTrue(category1.equals(category2));
    }
}
