// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

public class Category_hashCode_5a2657087a_Test {

    private Category category1;
    private Category category2;
    private Category category3;

    @BeforeEach
    public void setUp() {
        category1 = new Category("Cat1", "Description1");
        category2 = new Category("Cat2", "Description2");
        category3 = new Category("Cat1", "Description3");
    }

    @Test
    public void testHashCode() {
        int hash1 = category1.hashCode();
        int hash2 = category2.hashCode();
        int hash3 = category3.hashCode();

        // Categories with different names should have different hash codes
        assertNotEquals(hash1, hash2);

        // Categories with the same name should have the same hash code
        assertEquals(hash1, hash3);
    }
}
