/*
Test generated by RoostGPT for test GeminiTest using AI Type Vertex AI and AI Model gemini-pro

 You have been asked to write test scenarios to validate the business logic of the equals method for the Country class.

**Test Scenario 1:**
- Test Setup: Create two Country objects with the same isoCode value.
- Expected Result: The equals method should return true when both objects have the same isoCode value.

**Test Scenario 2:**
- Test Setup: Create two Country objects with different isoCode values.
- Expected Result: The equals method should return false when both objects have different isoCode values.

**Test Scenario 3:**
- Test Setup: Create two Country objects with null isoCode values.
- Expected Result: The equals method should return false when both objects have null isoCode values.

**Test Scenario 4:**
- Test Setup: Create a Country object and compare it with an object of a different class.
- Expected Result: The equals method should return false when comparing a Country object with an object of a different class.

**Test Scenario 5:**
- Test Setup: Create a Country object and compare it with a null object.
- Expected Result: The equals method should return false when comparing a Country object with a null object.
*/
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Country_equals_f2d574000d_Test {

	@ParameterizedTest
	@CsvSource({
		"IND, IND, true",
		"IND, USA, false",
		"null, null, false",
		"IND, IND, true"
	})
	void testEquals(String isoCode1, String isoCode2, boolean expected) {
		Country country1 = new Country();
		country1.setIsoCode(isoCode1);
		Country country2 = new Country();
		country2.setIsoCode(isoCode2);
		assertEquals(expected, country1.equals(country2));
	}

	@Test
	void testEquals_WithNull() {
		Country country1 = new Country();
		country1.setIsoCode("IND");
		assertEquals(false, country1.equals(null));
	}

	@Test
	void testEquals_WithDifferentClass() {
		Country country1 = new Country();
		country1.setIsoCode("IND");
		String str = "Hello";
		assertEquals(false, country1.equals(str));
	}
}
