// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Objects;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Country_hashCode_5a2657087a_Test {

    private Country country;

    @BeforeEach
    public void setup() {
        country = new Country();
    }

    @Test
    public void testHashCodeWithNullIsoCode() {
        country.setIsoCode(null);
        int expectedHashCode = Objects.hash((String) null);
        assertEquals(expectedHashCode, country.hashCode());
    }

    @Test
    public void testHashCodeWithEmptyIsoCode() {
        country.setIsoCode("");
        int expectedHashCode = Objects.hash("");
        assertEquals(expectedHashCode, country.hashCode());
    }

    @Test
    public void testHashCodeWithNonEmptyIsoCode() {
        country.setIsoCode("US");
        int expectedHashCode = Objects.hash("US");
        assertEquals(expectedHashCode, country.hashCode());
    }
}
