// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Country_equals_f2d574000d_Test {

    @Test
    public void testEquals() {
        Country country1 = new Country("isoCode1","name1","printableName1","iso31","numcode1");
        Country country2 = new Country("isoCode1","name2","printableName2","iso32","numcode2");
        Country country3 = new Country("isoCode3","name3","printableName3","iso33","numcode3");

        // Test for equality when two objects are the same
        assertTrue(country1.equals(country1));

        // Test for equality when two objects have the same isoCode
        assertTrue(country1.equals(country2));

        // Test for inequality when two objects have different isoCode
        assertFalse(country1.equals(country3));

        // Test for inequality when compared object is null
        assertFalse(country1.equals(null));

        // Test for inequality when compared object is of different class
        assertFalse(country1.equals("StringObject"));
    }
}
