// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class Customer_equals_f2d574000d_Test {

    private Customer customer1;
    private Customer customer2;

    @BeforeEach
    void setUp() {
        customer1 = new Customer();
        customer1.setLogin("testLogin1");
        
        customer2 = new Customer();
        customer2.setLogin("testLogin2");
    }

    @Test
    void testEquals_SameObject() {
        assertTrue(customer1.equals(customer1));
    }

    @Test
    void testEquals_SameLogin() {
        customer2.setLogin("testLogin1");
        assertTrue(customer1.equals(customer2));
    }

    @Test
    void testEquals_DifferentLogin() {
        assertFalse(customer1.equals(customer2));
    }

    @Test
    void testEquals_Null() {
        assertFalse(customer1.equals(null));
    }

    @Test
    void testEquals_DifferentClass() {
        assertFalse(customer1.equals(new Address()));
    }
}
