// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Item_hashCode_5a2657087a_Test {

    private Item item1, item2;

    @BeforeEach
    void setUp() {
        Product product = new Product("Product1", "Description1", null);
        item1 = new Item("Item1", 10.0f, "path1", "Description1", product);
        item2 = new Item("Item1", 10.0f, "path1", "Description1", product);
    }

    @Test
    void testHashCodeSameObject() {
        assertEquals(item1.hashCode(), item1.hashCode());
    }

    @Test
    void testHashCodeDifferentObjectSameData() {
        assertEquals(item1.hashCode(), item2.hashCode());
    }

    @Test
    void testHashCodeDifferentObjectDifferentData() {
        item2.setName("Item2");
        assertNotEquals(item1.hashCode(), item2.hashCode());
    }

    @Test
    void testHashCodeNullObject() {
        Item nullItem = null;
        assertNotEquals(item1.hashCode(), nullItem);
    }
}
