// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.Test;
import org.junit.Assert;
import nl.jqno.equalsverifier.EqualsVerifier;

public class Item_hashCode_5a2657087a_Test {

    @Test
    public void testHashCode() {
        Item item1 = new Item();
        item1.setName("Dog Food");
        item1.setDescription("Premium Quality");

        Item item2 = new Item();
        item2.setName("Dog Food");
        item2.setDescription("Premium Quality");

        Assert.assertEquals(item1.hashCode(), item2.hashCode());
    }

    @Test
    public void testHashCodeNegative() {
        Item item1 = new Item();
        item1.setName("Dog Food");
        item1.setDescription("Premium Quality");

        Item item2 = new Item();
        item2.setName("Cat Food");
        item2.setDescription("Premium Quality");

        Assert.assertNotEquals(item1.hashCode(), item2.hashCode());
    }

    @Test
    public void hashCodeContract() {
        EqualsVerifier.forClass(Item.class).verify();
    }
}
