// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class Item_equals_f2d574000d_Test {

    private Item itemUnderTest;

    @BeforeEach
    public void setUp() {
        itemUnderTest = new Item();
    }

    @Test
    public void testEquals_sameObject() {
        assertTrue(itemUnderTest.equals(itemUnderTest));
    }

    @Test
    public void testEquals_nullObject() {
        assertFalse(itemUnderTest.equals(null));
    }

    @Test
    public void testEquals_differentClass() {
        assertFalse(itemUnderTest.equals(new Product()));
    }

    @Test
    public void testEquals_sameValues() {
        itemUnderTest.setName("TestName");
        itemUnderTest.setDescription("TestDescription");
        Item anotherItem = new Item("TestName", 1.0F, "TestImagePath", "TestDescription", new Product());
        assertTrue(itemUnderTest.equals(anotherItem));
    }

    @Test
    public void testEquals_differentValues() {
        itemUnderTest.setName("TestName");
        itemUnderTest.setDescription("TestDescription");
        Item anotherItem = new Item("DifferentName", 1.0F, "TestImagePath", "DifferentDescription", new Product());
        assertFalse(itemUnderTest.equals(anotherItem));
    }
}
