// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class OrderLine_hashCode_5a2657087a_Test {

    private OrderLine orderLine1, orderLine2;
    private Item item1, item2;

    @BeforeEach
    public void setUp() {
        item1 = new Item("Item1", 20.0f, "path1", "desc1", new Product());
        item2 = new Item("Item2", 25.0f, "path2", "desc2", new Product());

        orderLine1 = new OrderLine(5, item1);
        orderLine2 = new OrderLine(5, item2);
    }

    @Test
    public void testHashCode_SameObject() {
        assertEquals(orderLine1.hashCode(), orderLine1.hashCode());
    }

    @Test
    public void testHashCode_DifferentObjectsSameProperties() {
        OrderLine anotherOrderLine = new OrderLine(5, item1);
        assertEquals(orderLine1.hashCode(), anotherOrderLine.hashCode());
    }

    @Test
    public void testHashCode_DifferentObjectsDifferentProperties() {
        assertNotEquals(orderLine1.hashCode(), orderLine2.hashCode());
    }

    @Test
    public void testHashCode_DifferentObjectsSameQuantityDifferentItem() {
        OrderLine anotherOrderLine = new OrderLine(5, item2);
        assertNotEquals(orderLine1.hashCode(), anotherOrderLine.hashCode());
    }

    @Test
    public void testHashCode_DifferentObjectsDifferentQuantitySameItem() {
        OrderLine anotherOrderLine = new OrderLine(10, item1);
        assertNotEquals(orderLine1.hashCode(), anotherOrderLine.hashCode());
    }
}
