// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class OrderLine_equals_f2d574000d_Test {

    private OrderLine orderLine1;
    private OrderLine orderLine2;
    private Item item1;
    private Item item2;
    
    @Before
    public void setUp() {
        item1 = new Item();
        item1.setId(1L);
        item1.setName("Item1");
        item1.setUnitCost(10.0f);

        item2 = new Item();
        item2.setId(2L);
        item2.setName("Item2");
        item2.setUnitCost(20.0f);

        orderLine1 = new OrderLine(5, item1);
        orderLine2 = new OrderLine(5, item1);
    }

    @Test
    public void testEqualsSameObject() {
        assertTrue(orderLine1.equals(orderLine1));
    }

    @Test
    public void testEqualsDifferentObjectSameData() {
        assertTrue(orderLine1.equals(orderLine2));
    }

    @Test
    public void testEqualsDifferentObjectDifferentData() {
        orderLine2.setItem(item2);
        assertFalse(orderLine1.equals(orderLine2));
    }

    @Test
    public void testEqualsNullObject() {
        assertFalse(orderLine1.equals(null));
    }

    @Test
    public void testEqualsDifferentClass() {
        assertFalse(orderLine1.equals(item1));
    }
}
