// Test generated by RoostGPT for test JavyaUnitTesting using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.model;

import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import nl.jqno.equalsverifier.EqualsVerifier;
import java.util.Objects;

public class Product_hashCode_5a2657087a_Test {

    @Test
    public void testHashCode() {
        Product product1 = new Product("Product1", "This is Product1", new Category("Category1", "This is Category1"));
        Product product2 = new Product("Product1", "This is Product1", new Category("Category1", "This is Category1"));

        int hashCode1 = product1.hashCode();
        int hashCode2 = product2.hashCode();

        assertEquals(hashCode1, hashCode2);
    }

    @Test
    public void testHashCodeWithDifferentObjects() {
        Product product1 = new Product("Product1", "This is Product1", new Category("Category1", "This is Category1"));
        Product product2 = new Product("Product2", "This is Product2", new Category("Category2", "This is Category2"));

        int hashCode1 = product1.hashCode();
        int hashCode2 = product2.hashCode();

        assertNotEquals(hashCode1, hashCode2);
    }

    @Test
    public void testHashCodeForNullValues() {
        Product product = new Product(null, null, null);

        int hashCode = product.hashCode();

        assertEquals(Objects.hash(null, null), hashCode);
    }

    @Test
    public void equalsContract() {
        EqualsVerifier.forClass(Product.class).verify();
    }
}
